# Generated by Django 5.1.4 on 2025-02-01 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bp_code', models.CharField(max_length=50, unique=True)),
                ('term', models.CharField(blank=True, max_length=100, null=True)),
                ('business_name', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=15)),
                ('alternate_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('landline', models.CharField(blank=True, max_length=15, null=True)),
                ('business_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('door_no', models.CharField(blank=True, max_length=50, null=True)),
                ('shop_no', models.CharField(blank=True, max_length=50, null=True)),
                ('complex_name', models.CharField(blank=True, max_length=255, null=True)),
                ('building_name', models.CharField(blank=True, max_length=255, null=True)),
                ('street_name', models.CharField(blank=True, max_length=255, null=True)),
                ('area', models.CharField(blank=True, max_length=255, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('location_guide', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessPartnerKYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bis_no', models.CharField(blank=True, max_length=50, null=True)),
                ('gst_no', models.CharField(blank=True, max_length=50, null=True)),
                ('msme_no', models.CharField(blank=True, max_length=50, null=True)),
                ('pan_no', models.CharField(blank=True, max_length=10, null=True)),
                ('tan_no', models.CharField(blank=True, max_length=10, null=True)),
                ('aadhar_no', models.CharField(blank=True, max_length=12, null=True)),
                ('aadhar_no_2', models.CharField(blank=True, max_length=12, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('account_name', models.CharField(blank=True, max_length=255, null=True)),
                ('account_no', models.CharField(blank=True, max_length=50, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=20, null=True)),
                ('branch', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_city', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_state', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('bp_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_details', to='BusinessPartner.businesspartner')),
            ],
        ),
    ]
