# Generated by Django 5.1.4 on 2025-02-02 15:39

import BusinessPartner.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessPartner', '0002_remove_businesspartnerkyc_aadhar_no_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businesspartnerkyc',
            old_name='aadhar_no_back',
            new_name='aadhar_back_image',
        ),
        migrations.RenameField(
            model_name='businesspartnerkyc',
            old_name='aadhar_no_front',
            new_name='aadhar_front_image',
        ),
        migrations.AddField(
            model_name='businesspartnerkyc',
            name='pan_card_image',
            field=models.ImageField(blank=True, null=True, upload_to='pan_card'),
        ),
        migrations.AlterField(
            model_name='businesspartnerkyc',
            name='aadhar_no',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[BusinessPartner.models.validate_aadhar_no]),
        ),
        migrations.AlterField(
            model_name='businesspartnerkyc',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[BusinessPartner.models.validate_ifsc_code]),
        ),
        migrations.AlterField(
            model_name='businesspartnerkyc',
            name='msme_no',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[BusinessPartner.models.validate_msme_no]),
        ),
        migrations.AlterField(
            model_name='businesspartnerkyc',
            name='tan_no',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[BusinessPartner.models.validate_pan_number]),
        ),
    ]
