# Generated by Django 5.1.4 on 2025-02-04 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessPartner', '0004_businesspartner_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesspartner',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='businesspartner',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='businesspartner',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BusinessPartner', to=settings.AUTH_USER_MODEL),
        ),
    ]
