# Generated by Django 5.1.5 on 2025-03-19 05:18

import BusinessPartner.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessPartner', '0006_alter_businesspartner_alternate_mobile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='businesspartner',
            old_name='name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='businesspartnerkyc',
            name='aadhar_back_image',
        ),
        migrations.RemoveField(
            model_name='businesspartnerkyc',
            name='aadhar_front_image',
        ),
        migrations.RemoveField(
            model_name='businesspartnerkyc',
            name='pan_card_image',
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='alternate_landline',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='freezed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='map_location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='more',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='refered_by',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='referer_mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='revoked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('freezed', 'Freezed'), ('revoked', 'Revoked')], default='approved', max_length=10),
        ),
        migrations.AddField(
            model_name='businesspartnerkyc',
            name='aadhar_attach',
            field=models.FileField(default='', upload_to='attachments/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businesspartnerkyc',
            name='bis_attachment',
            field=models.ImageField(default='', upload_to='attachments/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businesspartnerkyc',
            name='freezed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businesspartnerkyc',
            name='gst_attachment',
            field=models.ImageField(default='', upload_to='attachments/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businesspartnerkyc',
            name='image',
            field=models.ImageField(default='', upload_to='kyc/business_partner/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businesspartnerkyc',
            name='msme_attachment',
            field=models.ImageField(default='', upload_to='attachments/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businesspartnerkyc',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businesspartnerkyc',
            name='pan_attachment',
            field=models.ImageField(default='', upload_to='attachments/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businesspartnerkyc',
            name='revoked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businesspartnerkyc',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('freezed', 'Freezed'), ('revoked', 'Revoked')], default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businesspartnerkyc',
            name='tan_attachment',
            field=models.ImageField(default='', upload_to='attachments/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='businesspartner',
            name='alternate_mobile',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[BusinessPartner.models.validate_mobile_no]),
        ),
        migrations.AlterField(
            model_name='businesspartner',
            name='business_email',
            field=models.EmailField(default='', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='businesspartner',
            name='email',
            field=models.EmailField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='businesspartner',
            name='pincode',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='businesspartner',
            name='term',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='businesspartnerkyc',
            name='aadhar_no',
            field=models.CharField(default=list, max_length=12, validators=[BusinessPartner.models.validate_aadhar_no]),
        ),
        migrations.AlterField(
            model_name='businesspartnerkyc',
            name='account_no',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='businesspartnerkyc',
            name='bank_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='businesspartnerkyc',
            name='bis_no',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='businesspartnerkyc',
            name='branch',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='businesspartnerkyc',
            name='gst_no',
            field=models.CharField(default='', max_length=50, validators=[BusinessPartner.models.validate_gst_number]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='businesspartnerkyc',
            name='ifsc_code',
            field=models.CharField(default='', max_length=20, validators=[BusinessPartner.models.validate_ifsc_code]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='businesspartnerkyc',
            name='msme_no',
            field=models.CharField(default='', max_length=50, validators=[BusinessPartner.models.validate_msme_no]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='businesspartnerkyc',
            name='pan_no',
            field=models.CharField(default='', max_length=10, validators=[BusinessPartner.models.validate_pan_number]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='businesspartnerkyc',
            name='tan_no',
            field=models.CharField(default='', max_length=10, validators=[BusinessPartner.models.validate_pan_number]),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='businesspartner',
            constraint=models.UniqueConstraint(fields=('business_email',), name='unique_email_ci'),
        ),
    ]
