# Generated by Django 5.1.5 on 2025-04-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessPartner', '0007_rename_name_businesspartner_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspartner',
            name='role',
            field=models.CharField(blank=True, choices=[('BUYER', 'BUYER'), ('CRAFTSMAN', 'CRAFTSMAN')], max_length=20, null=True),
        ),
    ]
