# Generated by Django 5.1.5 on 2025-04-02 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessPartner', '0009_alter_businesspartner_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesspartner',
            name='business_email',
            field=models.EmailField(max_length=254),
        ),
    ]
