# Generated by Django 5.1.5 on 2025-04-03 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessPartner', '0012_alter_businesspartner_business_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesspartner',
            name='business_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
