# Generated by Django 5.1.5 on 2025-04-04 06:34

import BusinessPartner.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessPartner', '0016_alter_businesspartnerkyc_bis_attachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesspartnerkyc',
            name='aadhar_attach',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
        migrations.AlterField(
            model_name='businesspartnerkyc',
            name='aadhar_no',
            field=models.CharField(blank=True, default=list, max_length=12, null=True, validators=[BusinessPartner.models.validate_aadhar_no]),
        ),
        migrations.AlterField(
            model_name='businesspartnerkyc',
            name='account_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='businesspartnerkyc',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='businesspartnerkyc',
            name='branch',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='businesspartnerkyc',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[BusinessPartner.models.validate_ifsc_code]),
        ),
        migrations.AlterField(
            model_name='businesspartnerkyc',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/business_partner/'),
        ),
        migrations.AlterField(
            model_name='businesspartnerkyc',
            name='msme_attachment',
            field=models.ImageField(blank=True, null=True, upload_to='attachments/'),
        ),
        migrations.AlterField(
            model_name='businesspartnerkyc',
            name='msme_no',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[BusinessPartner.models.validate_msme_no]),
        ),
        migrations.AlterField(
            model_name='businesspartnerkyc',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='businesspartnerkyc',
            name='pan_attachment',
            field=models.ImageField(blank=True, null=True, upload_to='attachments/'),
        ),
        migrations.AlterField(
            model_name='businesspartnerkyc',
            name='pan_no',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[BusinessPartner.models.validate_pan_number]),
        ),
        migrations.AlterField(
            model_name='businesspartnerkyc',
            name='tan_attachment',
            field=models.ImageField(blank=True, null=True, upload_to='attachments/'),
        ),
        migrations.AlterField(
            model_name='businesspartnerkyc',
            name='tan_no',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[BusinessPartner.models.validate_pan_number]),
        ),
    ]
