# Generated by Django 5.1.5 on 2025-04-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessPartner', '0017_alter_businesspartnerkyc_aadhar_attach_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesspartner',
            name='business_email',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
