# Generated by Django 5.1.5 on 2025-04-05 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessPartner', '0020_alter_businesspartner_business_email'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='businesspartner',
            name='unique_email_ci',
        ),
    ]
