# Generated by Django 5.1.5 on 2025-04-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessPartner', '0021_remove_businesspartner_unique_email_ci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesspartner',
            name='bp_code',
            field=models.CharField(choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3'), ('CH', 'CH')], max_length=50, unique=True),
        ),
    ]
