# Generated by Django 5.1.5 on 2025-04-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessPartner', '0023_alter_businesspartner_bp_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesspartner',
            name='business_email',
            field=models.EmailField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
