# Generated by Django 5.1.5 on 2025-04-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessPartner', '0025_alter_businesspartner_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesspartner',
            name='term',
            field=models.CharField(choices=[('T1', 'T1-Credit 30 Days'), ('T2', 'T2-Credit 45 Days'), ('T3', 'T3-Credit 60 Days'), ('CH', 'CH-Cash Customer')], max_length=100),
        ),
    ]
