# Generated by Django 5.1.5 on 2025-04-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessPartner', '0026_alter_businesspartner_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesspartner',
            name='business_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
