# Generated by Django 5.1.5 on 2025-04-17 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessPartner', '0027_alter_businesspartner_business_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspartner',
            name='partner_type',
            field=models.CharField(choices=[('CRAFTSMAN', 'Craftsman'), ('BUYER', 'Buyer')], default='', max_length=50),
            preserve_default=False,
        ),
    ]
