# Generated by Django 5.1.5 on 2025-04-17 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessPartner', '0028_businesspartner_partner_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesspartner',
            name='partner_type',
        ),
    ]
