# Generated by Django 5.1.4 on 2025-02-27 08:50

import django.core.validators
import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleDashboardMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('super_admin', 'Project Owner'), ('admin', 'Super User'), ('staff', 'Key User'), ('craftsman', 'Craftsman'), ('seller', 'End User'), ('customer', 'One Time User')], max_length=50)),
                ('dashboard_url', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='resuser',
            name='permission_group',
        ),
        migrations.AlterModelManagers(
            name='resuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='resuser',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='resuser',
            name='role',
        ),
        migrations.AddField(
            model_name='resuser',
            name='approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resuser',
            name='archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resuser',
            name='copy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resuser',
            name='custom_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resuser',
            name='delete_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resuser',
            name='delete_perm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resuser',
            name='download',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resuser',
            name='edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resuser',
            name='full_control',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resuser',
            name='manage_roles',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resuser',
            name='print_perm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resuser',
            name='reject',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resuser',
            name='restore_perm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resuser',
            name='screenshot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resuser',
            name='share',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resuser',
            name='transfer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resuser',
            name='user_code',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='resuser',
            name='user_state',
            field=models.CharField(choices=[('internal', 'INTERNAL USER'), ('external', 'EXTERNAL USER')], default='internal', max_length=50),
        ),
        migrations.AddField(
            model_name='resuser',
            name='view_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='resuser',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resuser',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='resuser',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resuser',
            name='email_id',
            field=models.EmailField(max_length=254, null=True, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='resuser',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='resuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='resuser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='custom_users', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='resuser',
            name='mobile_no',
            field=models.CharField(max_length=15, validators=[user.models.validate_mobile_no]),
        ),
        migrations.AlterField(
            model_name='resuser',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='resuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='User/Profile'),
        ),
        migrations.AlterField(
            model_name='resuser',
            name='role_name',
            field=models.CharField(choices=[('super_admin', 'Project Owner'), ('admin', 'Super User'), ('staff', 'Key User'), ('craftsman', 'Craftsman'), ('seller', 'End User'), ('customer', 'One Time User')], default='super_admin', max_length=50),
        ),
        migrations.AlterField(
            model_name='resuser',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resuser',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='resuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='resuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='custom_user_permissions', to='auth.permission'),
        ),
        migrations.DeleteModel(
            name='PermissionGroup',
        ),
    ]
