# Generated by Django 5.1.4 on 2025-03-08 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessPartner', '0006_alter_businesspartner_alternate_mobile_and_more'),
        ('user', '0002_roledashboardmapping_remove_resuser_permission_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resuser',
            name='bp_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='BusinessPartner.businesspartner'),
        ),
        migrations.AddField(
            model_name='resuser',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
