# Generated by Django 5.1.7 on 2025-03-20 19:47

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0009_alter_resuser_bp_code'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='resuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='resuser',
            name='delete_perm',
        ),
        migrations.RemoveField(
            model_name='resuser',
            name='restore_perm',
        ),
        migrations.AddField(
            model_name='resuser',
            name='delete',
            field=models.BooleanField(default=False, verbose_name='Delete'),
        ),
        migrations.AddField(
            model_name='resuser',
            name='restore',
            field=models.BooleanField(default=False, verbose_name='Restore'),
        ),
        migrations.AlterField(
            model_name='resuser',
            name='approve',
            field=models.BooleanField(default=False, verbose_name='Approve'),
        ),
        migrations.AlterField(
            model_name='resuser',
            name='archive',
            field=models.BooleanField(default=False, verbose_name='Archive'),
        ),
        migrations.AlterField(
            model_name='resuser',
            name='copy',
            field=models.BooleanField(default=False, verbose_name='Copy'),
        ),
        migrations.AlterField(
            model_name='resuser',
            name='custom_access',
            field=models.BooleanField(default=False, verbose_name='Custom Access'),
        ),
        migrations.AlterField(
            model_name='resuser',
            name='download',
            field=models.BooleanField(default=False, verbose_name='Download'),
        ),
        migrations.AlterField(
            model_name='resuser',
            name='edit',
            field=models.BooleanField(default=False, verbose_name='Edit'),
        ),
        migrations.AlterField(
            model_name='resuser',
            name='full_control',
            field=models.BooleanField(default=False, verbose_name='Full Control'),
        ),
        migrations.AlterField(
            model_name='resuser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='custom_users', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='resuser',
            name='manage_roles',
            field=models.BooleanField(default=False, verbose_name='Manage Roles'),
        ),
        migrations.AlterField(
            model_name='resuser',
            name='print_perm',
            field=models.BooleanField(default=False, verbose_name='Print'),
        ),
        migrations.AlterField(
            model_name='resuser',
            name='reject',
            field=models.BooleanField(default=False, verbose_name='Reject'),
        ),
        migrations.AlterField(
            model_name='resuser',
            name='screenshot',
            field=models.BooleanField(default=False, verbose_name='Screenshot'),
        ),
        migrations.AlterField(
            model_name='resuser',
            name='share',
            field=models.BooleanField(default=False, verbose_name='Share'),
        ),
        migrations.AlterField(
            model_name='resuser',
            name='transfer',
            field=models.BooleanField(default=False, verbose_name='Transfer'),
        ),
        migrations.AlterField(
            model_name='resuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='custom_users', to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='resuser',
            name='view_only',
            field=models.BooleanField(default=False, verbose_name='View Only'),
        ),
    ]
