# Generated by Django 5.1.5 on 2025-03-24 12:19

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_resuser_role_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resuser',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[user.models.validate_mobile_no]),
        ),
    ]
