# Generated by Django 5.1.5 on 2025-03-25 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_resuser_full_name_alter_resuser_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resuser',
            name='email_id',
            field=models.EmailField(default='', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
