# Generated by Django 5.1.5 on 2025-03-25 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_resuser_email_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resuser',
            name='role_name',
            field=models.CharField(choices=[('Project Owner', 'Project Owner'), ('Super Admin', 'Super Admin'), ('Admin', 'Admin'), ('Key User', 'Key User'), ('User', 'User'), ('Craftsman', 'Craftsman'), ('Walking Customer', 'Walking Customer')], max_length=50),
        ),
        migrations.AlterField(
            model_name='roledashboardmapping',
            name='role',
            field=models.CharField(choices=[('Project Owner', 'Project Owner'), ('Super Admin', 'Super Admin'), ('Admin', 'Admin'), ('Key User', 'Key User'), ('User', 'User'), ('Craftsman', 'Craftsman'), ('Walking Customer', 'Walking Customer')], max_length=50),
        ),
    ]
