# Generated by Django 5.1.5 on 2025-04-26 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessPartner', '0029_remove_businesspartner_partner_type'),
        ('order', '0002_order_rejected_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reassigned_orders', to='BusinessPartner.businesspartner'),
        ),
    ]
