# Generated by Django 5.1.5 on 2025-04-30 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='segment',
            field=models.CharField(blank=True, choices=[('luxury', 'Luxury'), ('standard', 'Standard'), ('budget', 'Budget')], max_length=50, null=True),
        ),
    ]
