# Generated by Django 5.1.5 on 2025-05-03 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_rejection_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='rejection_reason',
            field=models.CharField(blank=True, choices=[('material_unavailable', 'Material Unavailable'), ('low_quality_material', 'Material Quality Too Low'), ('supplier_delays', 'Supplier Delays'), ('material_cost_increase', 'Material Cost Increased Unacceptably'), ('design_complexity', 'Design Too Complex'), ('design_errors', 'Design Has Errors/Flaws'), ('technical_infeasible', 'Technically Not Feasible'), ('3d_model_problems', '3D Model Cannot Be Executed'), ('size_constraints', 'Size/Proportions Not Workable'), ('time_constraints', 'Cannot Meet Deadline'), ('overbooked', 'Overbooked (No Capacity)'), ('shipping_restrictions', 'Shipping/Delivery Not Possible'), ('quality_concerns', 'Quality Standards Cannot Be Met'), ('finishing_issues', 'Cannot Achieve Desired Finish'), ('durability_risk', 'Durability Compromised'), ('customer_changes', 'Customer Changed Requirements'), ('customer_unreachable', 'Customer Unreachable'), ('customer_cancellation', 'Customer Canceled Mid-Process'), ('customer_dispute', 'Customer Dispute (Legal/Contract)'), ('pricing_issues', 'Pricing Dispute'), ('payment_issues', 'Payment Not Secured'), ('budget_mismatch', 'Budget Too Low for Requirements'), ('incomplete_specs', 'Incomplete Specifications'), ('documentation_missing', 'Legal/Mandatory Docs Missing'), ('policy_violation', 'Violates Shop Policies'), ('force_majeure', 'Force Majeure (Natural Disaster, etc.)'), ('other', 'Other Reason (Specify in Notes)')], help_text='Reason for rejecting the order', max_length=50, null=True),
        ),
    ]
