# Generated by Django 5.1.5 on 2025-05-03 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_order_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rejection_notes',
            field=models.TextField(blank=True, help_text="Additional details (required if 'Other Reason' is selected)", null=True),
        ),
    ]
