# Generated by Django 5.1.5 on 2025-05-03 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_remove_order_rejection_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
